import { useCallback, useEffect, useRef, useState } from 'react';
import { describeEvent } from '../api-client.js';
import { getRevealGroups } from '../reveal.js';
import AgentActivity from './AgentActivity.jsx';
import EventControls from './EventControls.jsx';
import Icon from './Icon.jsx';
import ResponsePanel from './ResponsePanel.jsx';
import SupplierBoard from './SupplierBoard.jsx';

// Live mode: real suppliers and events from MongoDB, real propagation and
// narration from backend/agent. Unlike demo mode this carries no scripted
// narrative, so it works for every seeded event rather than two.

const HOP_MS = 550; // the staggered reveal; one beat per cascade tier

export default function LiveWorkspace({ client, onUseDemo }) {
  const [network, setNetwork] = useState(null);
  const [loadError, setLoadError] = useState('');
  const [eventId, setEventId] = useState('');
  const [result, setResult] = useState(null);
  const [impacts, setImpacts] = useState({});
  const [hops, setHops] = useState(0);
  const [tiers, setTiers] = useState(0);
  const [stage, setStage] = useState(0);
  const [elapsed, setElapsed] = useState(0);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [tab, setTab] = useState('summary');
  const [filter, setFilter] = useState('all');
  const [supplierId, setSupplierId] = useState(null);
  const [regenerating, setRegenerating] = useState(false);

  const timers = useRef([]);
  const run = useRef(0);

  const clearTimers = useCallback(() => {
    timers.current.forEach(clearTimeout);
    timers.current = [];
  }, []);

  useEffect(() => () => { clearTimers(); run.current++; }, [clearTimers]);

  useEffect(() => {
    let live = true;
    (async () => {
      try {
        const [suppliers, events] = await Promise.all([client.getSuppliers(), client.getEvents()]);
        if (!live) return;
        setNetwork({ suppliers, events });
        setSupplierId(suppliers[0]?.id ?? null);
        // Default to the deepest cascade available — the most informative event.
        setEventId(events.find((event) => event.severity === 'high')?.id ?? events[0]?.id ?? '');
      } catch (cause) {
        if (live) setLoadError(cause.message);
      }
    })();
    return () => { live = false; };
  }, [client]);

  useEffect(() => {
    if (stage === 0 || stage === 4) return;
    const started = Date.now();
    const handle = setInterval(() => setElapsed(Math.round((Date.now() - started) / 1000)), 250);
    return () => clearInterval(handle);
  }, [stage]);

  function reset() {
    clearTimers();
    run.current++;
    setResult(null); setImpacts({}); setHops(0); setTiers(0); setStage(0);
    setElapsed(0); setError(''); setNotice(''); setTab('summary'); setRegenerating(false);
  }

  async function analyze() {
    reset();
    const attempt = ++run.current;
    setStage(1);

    let analysis;
    try {
      analysis = await client.analyze(eventId);
    } catch (cause) {
      if (attempt === run.current) { setError(cause.message); setStage(0); }
      return;
    }
    if (attempt !== run.current) return;

    // The backend owns which suppliers are affected; this only orders the reveal.
    const groups = getRevealGroups(analysis, network.suppliers);
    const direct = new Set(analysis.directly_affected);
    setTiers(Math.max(0, groups.length - 1));
    setStage(2);

    groups.forEach((group, index) => {
      const timer = setTimeout(() => {
        if (attempt !== run.current) return;
        setImpacts((current) => ({
          ...current,
          ...Object.fromEntries(group.map((id) => [id, direct.has(id) ? 'direct' : 'cascade'])),
        }));
        setHops(index);
        if (index === groups.length - 1) {
          setResult(analysis);
          setStage(4);
        }
      }, index * HOP_MS);
      timers.current.push(timer);
    });

    if (!groups.length) { setResult(analysis); setStage(4); }
  }

  async function regenerate() {
    if (!result) return;
    const attempt = run.current;
    setRegenerating(true); setNotice('');
    try {
      const { draft_report } = await client.regenerateDraft(result);
      if (attempt === run.current) {
        setResult((current) => ({ ...current, draft_report }));
        setNotice('Draft regenerated by the local model. Propagation was not recomputed.');
      }
    } catch (cause) {
      if (attempt === run.current) setNotice(cause.message);
    } finally {
      if (attempt === run.current) setRegenerating(false);
    }
  }

  async function copyDraft() {
    if (!result) return;
    const attempt = run.current;
    try {
      await navigator.clipboard.writeText(result.draft_report);
      if (attempt === run.current) setNotice('Draft copied to clipboard.');
    } catch {
      if (attempt === run.current) setNotice('Clipboard unavailable. Select and copy the draft text.');
    }
  }

  if (loadError) {
    return (
      <section className="disconnected-panel panel" aria-labelledby="live-error-title">
        <span className="connection-icon"><Icon name="plug" size={30} /></span>
        <h2 id="live-error-title">Cannot reach the local services</h2>
        <p>{loadError}</p>
        <div className="connection-list">
          <div><span>MongoDB</span><strong>docker start markovathon-mongo</strong></div>
          <div><span>Seed data</span><strong>python -m backend.data.seed</strong></div>
          <div><span>API</span><strong>uvicorn backend.api.main:app --port 8000</strong></div>
        </div>
        <button className="primary-button" onClick={onUseDemo}><Icon name="play" size={16} />Use demo mode instead</button>
        <small>Demo mode needs no backend.</small>
      </section>
    );
  }

  if (!network) {
    return <section className="result-panel panel" role="status"><div className="loading-title"><span className="spinner" /><strong>Connecting to local services…</strong></div></section>;
  }

  const busy = stage > 0 && stage < 4;

  return <>
    <section className="walkthrough panel" aria-label="Live incident">
      <div className="journey-body">
        <div className="stage-canvas" data-stage={stage}>
          <div className="stage-heading">
            <h2>Live workspace</h2>
            <p>Suppliers and events read from the local database. Exposure computed by the agent, wording written by the local model.</p>
          </div>
          <EventControls
            events={network.events}
            selectedId={eventId}
            onSelect={(id) => { reset(); setEventId(id); }}
            labelFor={describeEvent}
            busy={busy}
            regenerating={regenerating}
            completed={stage === 4}
            onRun={analyze}
            onReset={reset}
            canReset={stage !== 0 || Boolean(result)}
            live
          />
          {error && <p role="alert" className="error">{error}</p>}
          {stage >= 2 && <p className="stage-caption">
            Tier {hops} of {tiers} revealed
            {stage === 4 && result && ` · ${result.directly_affected.length} direct, ${result.cascading_affected.length} downstream`}
          </p>}
        </div>
        <aside className="evidence-ledger" aria-label="Pipeline">
          <div className="ledger-heading"><h3>Pipeline</h3></div>
          <p>Where each part of this answer comes from.</p>
          <div className="ledger-list">
            {[
              ['MongoDB', 'suppliers and events, local', stage >= 0],
              ['propagation.py', 'deterministic — no model', stage >= 2],
              ['local model', 'assessment and draft wording', stage === 4],
            ].map(([name, note, done]) => (
              <button key={name} disabled className={done ? 'selected' : ''}>
                <span className="ledger-id">{done ? '✓' : '·'}</span>
                <span><strong>{name}</strong><small>{note}</small></span>
              </button>
            ))}
          </div>
          <div className="ledger-note"><Icon name="shield" size={16} /><p>Every stage runs on this machine.</p></div>
        </aside>
      </div>
    </section>
    <ResponsePanel
      result={result} stage={stage} regenerating={regenerating} elapsed={elapsed}
      tab={tab} onTab={(value) => { setTab(value); setNotice(''); }}
      notice={notice} onCopy={copyDraft} onRegenerate={regenerate} live
    />
    <div className="supporting-network">
      <SupplierBoard suppliers={network.suppliers} selectedId={supplierId} onSelect={setSupplierId} impacts={impacts} filter={filter} onFilter={setFilter} />
      <AgentActivity client={client} />
    </div>
  </>;
}
