import React from 'react';
import {Interactive, interpolate, useCurrentFrame} from 'remotion';
import {Arrow, Caption, Check, Heading, Shell, clamp, colors, data} from '../ui';

const steps = data.analysis.draft_report.split('Recommended next steps:\n')[1].split('\n\n')[0].split('\n').map(line=>line.trim().replace(/^\d\. /,''));
const stepTimes = [1.35, 2.05, 2.75, 3.45];
const phaseTimes = [.2, .75, 1.3, 4.43];

export const Response:React.FC = ()=>{
 const f=useCurrentFrame();
 const fallback=f>=11.2*60;
 const summary=data.analysis.risk_summary.split('. ')[0]+'.';
 return <Shell time={77+f/60}>
  <Heading title="From exposure to an actionable response" sub="Resolved suppliers first. Reviewable wording second. A person approves the next step."/>
  <Interactive.Div name="Evidence to reviewable response" style={{position:'absolute',left:80,right:80,top:247,height:565,opacity:interpolate(f,[10.95*60,11.2*60],[1,0],clamp),translate:interpolate(f,[10.95*60,11.2*60],['0px 0px','0px -14px'],clamp)}}>
   <div style={{height:55,display:'flex',alignItems:'center',gap:16}}>{['Evidence resolved','Impact calculated','Draft prepared','Human approval'].map((label,i)=><React.Fragment key={label}><div style={{position:'relative',flex:1,overflow:'hidden',height:53,padding:'13px 20px',border:`1px solid ${i===3&&f>=phaseTimes[i]*60?'#ddbe83':colors.line}`,borderRadius:8,background:'white',display:'flex',alignItems:'center',gap:10,fontSize:22,fontWeight:600}}><span style={{position:'absolute',left:0,top:0,bottom:0,width:`${interpolate(f,[phaseTimes[i]*60,phaseTimes[i]*60+35],[0,100],clamp)}%`,background:i===3?'#fff2d9':'#edf3ff'}}/><span style={{position:'relative',width:23,height:23,borderRadius:20,background:i===3?'#a27421':colors.blue,color:'white',fontSize:15,display:'grid',placeItems:'center'}}>{i+1}</span><span style={{position:'relative'}}>{label}</span></div>{i<3&&<span style={{color:f>=phaseTimes[i+1]*60?colors.blue:'#bbc5d2'}}><Arrow/></span>}</React.Fragment>)}</div>
   <Interactive.Div name="Risk summary" style={{position:'absolute',left:0,top:76,width:590,height:489,background:'white',border:`1px solid ${colors.line}`,borderRadius:12,padding:27,opacity:interpolate(f,[0,22],[0,1],clamp),translate:interpolate(f,[0,28],['0px 18px','0px 0px'],clamp)}}>
    <div style={{fontSize:18,color:colors.muted,display:'flex',alignItems:'center',gap:8,marginBottom:10}}><Check size={18}/>Local supplier records · evt_004</div>
    <h3 style={{fontSize:27,margin:'0 0 18px'}}>Risk assessment</h3>
    <div style={{display:'flex',gap:27,paddingBottom:20,borderBottom:`1px solid ${colors.line}`,fontSize:19}}>{[{value:1,label:'direct',color:colors.red},{value:5,label:'downstream',color:colors.amber},{value:.961,label:'network risk',color:colors.red}].map((metric,i)=><div key={metric.label} style={{opacity:interpolate(f,[.6*60+i*7,.6*60+i*7+18],[0,1],clamp)}}><strong style={{fontSize:41,lineHeight:1.2,color:metric.color,fontVariantNumeric:'tabular-nums',display:'block'}}>{i===2?interpolate(f,[.75*60,1.55*60],[0,metric.value],clamp).toFixed(3):Math.round(interpolate(f,[.75*60,1.55*60],[0,metric.value],clamp))}</strong>{metric.label}</div>)}</div>
    <p style={{fontSize:22,lineHeight:1.55,margin:'18px 0 0',opacity:interpolate(f,[.7*60,1.2*60],[0,1],clamp)}}>{summary}</p>
    <div style={{position:'absolute',left:27,right:27,bottom:20,fontSize:18,color:colors.muted}}>Verified template excerpt · resolved dependency chain</div>
   </Interactive.Div>
   <Interactive.Div name="Readable response actions" style={{position:'absolute',left:614,right:0,top:76,height:489,background:'white',border:`1px solid ${colors.line}`,borderRadius:12,padding:'24px 27px',opacity:interpolate(f,[.8*60,1.15*60],[0,1],clamp),translate:interpolate(f,[.8*60,1.3*60],['20px 0px','0px 0px'],clamp)}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{fontSize:27,margin:0}}>Response draft</h3><span style={{fontSize:19,color:colors.amber,background:'#fff2d9',padding:'7px 12px',borderRadius:5,opacity:interpolate(f,[3.9*60,4.43*60],[.4,1],clamp)}}>Unsent · human review</span></div>
    <div style={{margin:'12px 0 13px',color:colors.muted,fontSize:19}}>To: Compliance Contact <span style={{padding:'0 10px',color:'#b1bdcc'}}>·</span> Recommended next steps</div>
    <div style={{display:'grid',gap:9}}>{steps.map((text,i)=><Interactive.Div name={`Draft action ${i+1}`} key={text} style={{position:'relative',display:'flex',alignItems:'center',gap:14,minHeight:66,border:`1px solid ${colors.line}`,borderRadius:7,padding:'10px 14px',overflow:'hidden',opacity:interpolate(f,[stepTimes[i]*60,stepTimes[i]*60+22],[0,1],clamp),translate:interpolate(f,[stepTimes[i]*60,stepTimes[i]*60+28],['15px 0px','0px 0px'],clamp)}}><span style={{position:'absolute',left:0,top:0,bottom:0,width:`${interpolate(f,[stepTimes[i]*60,stepTimes[i]*60+33],[0,100],clamp)}%`,background:'#f1f5fd'}}/><span style={{fontSize:18,fontWeight:650,color:colors.blue,position:'relative',minWidth:22}}>{i+1}.</span><span style={{position:'relative',fontSize:21,lineHeight:1.35}}>{text}</span></Interactive.Div>)}</div>
    <div style={{position:'absolute',left:27,right:27,bottom:19,display:'flex',alignItems:'center',gap:9,color:colors.amber,fontSize:18,opacity:interpolate(f,[4.2*60,4.6*60],[0,1],clamp)}}><span style={{width:7,height:7,borderRadius:10,background:colors.amber}}/>Prepared for approval · delivery is not connected</div>
   </Interactive.Div>
  </Interactive.Div>
  <Interactive.Div name="Recorded fallback route" style={{position:'absolute',left:80,right:80,top:247,height:565,border:`1px solid ${colors.line}`,borderRadius:12,background:'white',opacity:interpolate(f,[11.2*60,11.55*60],[0,1],clamp),translate:interpolate(f,[11.2*60,11.7*60],['0px 24px','0px 0px'],clamp),pointerEvents:fallback?'auto':'none'}}>
   <div style={{position:'absolute',left:30,top:25,right:30,display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3 style={{fontSize:27,margin:0}}>The response path stays available</h3><span style={{fontSize:18,color:colors.muted}}>Recorded local check</span></div>
   <div style={{position:'absolute',left:580,top:91,width:600,height:61,border:'1px solid #e3c895',borderRadius:9,background:'#fff6e7',color:colors.amber,display:'flex',justifyContent:'center',alignItems:'center',gap:12,fontSize:23,opacity:interpolate(f,[11.4*60,11.9*60],[0,1],clamp)}}><span style={{fontSize:26}}>×</span>Model endpoint unavailable</div>
   <svg width={1760} height={565} style={{position:'absolute',inset:0}}>
    <path d="M 425 220 C 425 123, 510 122, 580 122" fill="none" stroke="#d6b986" strokeWidth={2} strokeDasharray="7 7" opacity={interpolate(f,[11.8*60,12.3*60],[0,.7],clamp)}/>
    {[0,1].map((i)=><g key={i}><path d={`M ${527+i*572} 306 L ${621+i*572} 306`} fill="none" stroke="#dce3ed" strokeWidth={3}/><path d={`M ${527+i*572} 306 L ${621+i*572} 306`} fill="none" stroke={colors.blue} strokeWidth={4} pathLength={1} strokeDasharray="1" strokeDashoffset={interpolate(f,[(13.8+i*2.2)*60,(14.5+i*2.2)*60],[1,0],clamp)}/><circle cx={interpolate(f,[(13.8+i*2.2)*60,(14.5+i*2.2)*60],[527+i*572,621+i*572],clamp)} cy={306} r={7} fill={colors.blue} opacity={interpolate(f,[(13.8+i*2.2)*60,(13.95+i*2.2)*60,(14.45+i*2.2)*60,(14.6+i*2.2)*60],[0,1,1,0],clamp)}/></g>)}
   </svg>
   {[{title:'Deterministic analysis',sub:'Propagation + impact scores',result:'Network risk 0.961',at:12.6},{title:'Template wording',sub:'Risk summary + action steps',result:'Wording completed',at:14.9},{title:'Reviewable draft',sub:'Ready for a person to approve',result:'Unsent · delivery disconnected',at:17.1}].map((node,i)=><Interactive.Div name={`Fallback ${node.title}`} key={node.title} style={{position:'absolute',left:30+i*572,top:220,width:494,height:196,border:`1px solid ${f>=node.at*60?'#9cb7e9':colors.line}`,background:f>=node.at*60?'#f2f6ff':'#f8fafc',borderRadius:11,padding:25,opacity:interpolate(f,[(11.65+i*.16)*60,(12.1+i*.16)*60],[0,1],clamp),translate:interpolate(f,[node.at*60,node.at*60+23],['0px 6px','0px 0px'],clamp)}}><div style={{fontSize:19,color:f>=node.at*60?colors.blue:colors.muted,display:'flex',gap:8,alignItems:'center',marginBottom:10}}>{f>=node.at*60?<Check color={colors.blue} size={20}/>:<span style={{width:20,textAlign:'center'}}>·</span>}{f>=node.at*60?'Completed':'Local processing path'}</div><h4 style={{fontSize:27,lineHeight:1.3,margin:'0 0 8px'}}>{node.title}</h4><div style={{fontSize:20,color:colors.muted}}>{node.sub}</div><div style={{fontSize:19,color:i===2?colors.amber:colors.blue,marginTop:14,opacity:interpolate(f,[node.at*60,node.at*60+20],[0,1],clamp)}}>{node.result}</div></Interactive.Div>)}
   <div style={{position:'absolute',left:30,right:30,top:445,height:84,padding:'17px 22px',borderRadius:8,background:'#ecf5ef',display:'flex',justifyContent:'space-between',alignItems:'center',opacity:interpolate(f,[17.6*60,18*60],[0,1],clamp),translate:interpolate(f,[17.6*60,18.1*60],['0px 12px','0px 0px'],clamp)}}><div style={{display:'flex',alignItems:'center',gap:10,fontSize:24,color:colors.green}}><Check size={25}/>Analysis and template draft completed</div><div style={{textAlign:'right',color:colors.muted,fontSize:18,lineHeight:1.45}}><strong style={{fontSize:23,color:colors.green,fontVariantNumeric:'tabular-nums'}}>{data.fallback_seconds.toFixed(4)}s</strong> recorded execution<br/>Direct Python call · not HTTP latency</div></div>
  </Interactive.Div>
  <Caption text={fallback?'Model unavailable · analysis still completes · template wording':'Drafted for human approval · no message sent'}/>
 </Shell>;
};
